MACHINE=ta6le
INSTALLBIN=/usr/bin
INSTALLLIB=/usr/lib/csv8.0/${MACHINE}/

install: goscher.boot
	cp goscher.boot ${INSTALLLIB}
	ln -sf ${INSTALLBIN}/petite ${INSTALLBIN}/goscher

uninstall:
	rm -rf ${INSTALLBIN}/goscher
	rm -rf ${INSTALLLIB}/goscher.boot
